### ISSUE TITLE
Wonderful tutorial

### ISSUE THREAD

**Issue by imarotte** [Satyam/book-react-redux#13]
I am just learning react and redux when I found your tutorial. It has been amazingly helpful. Thank you so much for the time you've put into it. I am eager for chapter 21!

Thanks again, your work is much appreciated.

**Comment by Satyam** [comment]
Thanks for your kind words.  

The code for chapter 21 is actually uploaded:  https://github.com/Satyam/book-react-redux/tree/chapter-21-01  it deals with turning your app into an isomorphic one. You could download the code for chapters 20 and 21 and diff them to see the differences.

 I've been busy in my day job and I'm somewhat behind, but I'll catch up ASAP.

Satyam
